name: Generate xml sitemap

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://suchiguma.github.io
        drop-html-extension: true
        exclude-paths: /googlef1c326092f50715e.html /googlef1c326092f50715e /ChallengeMode /stage /videos /static /inserts

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7.0.5
      with:
        title: "Automated sitemap update"
        body: > 
          Automated changes.
        commit-message: "Automated sitemap update."
        branch: create-pull-request/sitemap
        delete-branch: true
